src/Entity/Annonces.php
<?php

namespace App\Entity;

use App\Repository\AnnoncesRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\ORM\Mapping\InheritanceType;
use Doctrine\ORM\Mapping\DiscriminatorColumn;
use Doctrine\ORM\Mapping\DiscriminatorMap;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\String\Slugger\AsciiSlugger;

/**
 * @ORM\Entity(repositoryClass=AnnoncesRepository::class)
 * @InheritanceType("JOINED")
 * @DiscriminatorColumn(name="discr", type="string")
 * @DiscriminatorMap({
 *     "Annonces" = "Annonces",
 *     "AnnonceVehicule" = "AnnonceVehicule",
 *     "AnnonceImmobilier" = "AnnonceImmobilier",
 *     "AnnonceBricoJardin" = "AnnonceBricoJardin",
 *     "AnnonceConsoleGaming" = "AnnonceConsoleGaming",
 *     "AnnonceDivers" = "AnnonceDivers",
 *     "AnnonceElectromenager" = "AnnonceElectromenager",
 *     "AnnonceImageEtSon" = "AnnonceImageEtSon",
 *     "AnnonceMaternite" = "AnnonceMaternite",
 *     "AnnonceMeubleDeco" = "AnnonceMeubleDeco",
 *     "AnnonceModeFemme" = "AnnonceModeFemme",
 *     "AnnonceModeEnfant" = "AnnonceModeEnfant",
 *     "AnnonceModeHomme" = "AnnonceModeHomme",
 *     "AnnonceMultimedia" = "AnnonceMultimedia",
 *     "AnnonceService" = "AnnonceService",
 *     "AnnonceSportLoisir" = "AnnonceSportLoisir",
 * })
 */
class Annonces
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $titre;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="float")
     */
    private $prix;

    /**
     * @ORM\Column(type="float")
     */
    private $proucentageTva;

    /**
     * @ORM\Column(type="datetime")
     */
    private $dateCreation;

    /**
     * @ORM\Column(type="datetime")
     */
    private $dateModification;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $statut;

    /**
     * @ORM\Column(type="boolean")
     */
    private $validationAdmin;

    /**
     * @ORM\ManyToOne(targetEntity=Categories::class, inversedBy="annonces" ,cascade={"persist"})
     * @ORM\JoinColumn(name="categorie_id", referencedColumnName="id", nullable=false)
     */
    private $categorie;

    /**
     * @ORM\ManyToOne(targetEntity=User::class,cascade={"persist"})
     * @ORM\JoinColumn(name="user_id", referencedColumnName="id", nullable=false)
     */
    private $user;

    /**
     * @ORM\OneToMany(targetEntity=Photo::class, mappedBy="annonces", cascade={"persist", "remove"})
     */
    private $photo;

    /**
     * @ORM\Column(type="integer")
     */
    private $visite;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $slug;

    /**
     * @ORM\ManyToOne(targetEntity=Categories::class)
     */
    private $sousCategorie;

    /**
     * @ORM\OneToMany(targetEntity=Location::class, mappedBy="annonce")
     */
    private $locations;

    /**
     * @ORM\ManyToOne(targetEntity=TypeLocation::class)
     */
    private $type;

    /**
     * @ORM\ManyToMany(targetEntity=User::class, mappedBy="favoris")
     */
    private $user_favoris;

    /**
     * @ORM\Column(type="float")
     */
    private $caution;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $urgent;

    /**
     * @ORM\Column(type="time", nullable=true)
     */
    private $heureDebut;

    /**
     * @ORM\Column(type="time", nullable=true)
     */
    private $heureFin;

    public function __construct()
    {
        $this->photo = new ArrayCollection();
        $this->dateCreation = new \Datetime();
        $this->locations = new ArrayCollection();
        $this->user_favoris = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getCategorie(): ?Categories
    {
        return $this->categorie;
    }

    public function setCategorie(?Categories $categorie): self
    {
        $this->categorie = $categorie;

        return $this;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(?string $titre): self
    {
        $this->titre = $titre;

        return $this;
    }

    public function getPrix(): ?float
    {
        return $this->prix;
    }

    public function setPrix(float $prix): self
    {
        $this->prix = $prix;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    /**
     * @param mixed $photo
     */
    public function setPhoto(): void
    {
        $this->photo = new ArrayCollection();
    }

    /**
     * @return Collection|Photo[]
     */
    public function getPhoto(): Collection
    {
        return $this->photo;
    }

    public function addPhoto(Photo $photo): self
    {
        if (!$this->photo->contains($photo)) {
            $this->photo[] = $photo;
            $photo->setAnnonces($this);
        }

        return $this;
    }

    public function removePhoto(Photo $photo): self
    {
        if ($this->photo->contains($photo)) {
            $this->photo->removeElement($photo);
            // set the owning side to null (unless already changed)
            if ($photo->getAnnonces() === $this) {
                $photo->setAnnonces(null);
            }
        }

        return $this;
    }

    public function getProucentageTva(): ?float
    {
        return $this->proucentageTva;
    }

    public function setProucentageTva(float $proucentageTva): self
    {
        $this->proucentageTva = $proucentageTva;

        return $this;
    }

    public function getDateCreation(): ?\DateTimeInterface
    {
        return $this->dateCreation;
    }

    public function setDateCreation(\DateTimeInterface $dateCreation): self
    {
        $this->dateCreation = $dateCreation;

        return $this;
    }

    public function getDateModification(): ?\DateTimeInterface
    {
        return $this->dateModification;
    }

    public function setDateModification(): self
    {
        $this->dateModification = new \Datetime();
        return $this;
    }

    public function getStatut(): ?string
    {
        return $this->statut;
    }

    public function setStatut(?string $statut): self
    {
        $this->statut = $statut;

        return $this;
    }

    public function getValidationAdmin(): ?bool
    {
        return $this->validationAdmin;
    }

    public function setValidationAdmin(bool $validationAdmin): self
    {
        $this->validationAdmin = $validationAdmin;

        return $this;
    }

    public function getVisite(): ?int
    {
        return $this->visite;
    }

    public function setVisite(int $visite): self
    {
        $this->visite = $visite;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(): self
    {
        $slugger    = new AsciiSlugger();
        $this->slug = $slugger->slug($this->titre);

        return $this;
    }

    public function getSousCategorie(): ?Categories
    {
        return $this->sousCategorie;
    }

    public function setSousCategorie(?Categories $sousCategorie): self
    {
        $this->sousCategorie = $sousCategorie;

        return $this;
    }

    /**
     * @return Collection|Location[]
     */
    public function getLocations(): Collection
    {
        return $this->locations;
    }

    public function addLocation(Location $location): self
    {
        if (!$this->locations->contains($location)) {
            $this->locations[] = $location;
            $location->setAnnonce($this);
        }

        return $this;
    }

    public function removeLocation(Location $location): self
    {
        if ($this->locations->contains($location)) {
            $this->locations->removeElement($location);
            // set the owning side to null (unless already changed)
            if ($location->getAnnonce() === $this) {
                $location->setAnnonce(null);
            }
        }

        return $this;
    }

    public function getType(): ?TypeLocation
    {
        return $this->type;
    }

    public function setType(?TypeLocation $type): self
    {
        $this->type = $type;

        return $this;
    }

    /**
     * @return Collection|User[]
     */
    public function getUserFavoris(): Collection
    {
        return $this->user_favoris;
    }

    public function addUserFavori(User $userFavori): self
    {
        if (!$this->user_favoris->contains($userFavori)) {
            $this->user_favoris[] = $userFavori;
            $userFavori->addFavori($this);
        }

        return $this;
    }

    public function removeUserFavori(User $userFavori): self
    {
        if ($this->user_favoris->contains($userFavori)) {
            $this->user_favoris->removeElement($userFavori);
            $userFavori->removeFavori($this);
        }

        return $this;
    }

    public function getCaution(): ?float
    {
        return $this->caution;
    }

    public function setCaution(float $caution): self
    {
        $this->caution = $caution;

        return $this;
    }

    public function getUrgent(): ?bool
    {
        return $this->urgent;
    }

    public function setUrgent(?bool $urgent): self
    {
        $this->urgent = $urgent;

        return $this;
    }

    public function getHeureDebut(): ?\DateTimeInterface
    {
        return $this->heureDebut;
    }

src/Controller/Annonce/CategoriesController.php
<?php

namespace App\Controller\Annonce;

use App\Entity\Categories;
use App\Form\CategoriesType;
use App\Repository\CategoriesRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/categories")
 */
class CategoriesController extends AbstractController
{
    /**
     * @Route("/", name="categories_index", methods={"GET"})
     */
    public function index(CategoriesRepository $categoriesRepository): Response
    {
        return $this->render('categories/index.html.twig', [
            'categories' => $categoriesRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="categories_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $category = new Categories();
        $form = $this->createForm(CategoriesType::class, $category);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($category);
            $entityManager->flush();

            return $this->redirectToRoute('categories_index');
        }

        return $this->render('categories/new.html.twig', [
            'category' => $category,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="categories_show", methods={"GET"})
     */
    public function show(Categories $category): Response
    {
        return $this->render('categories/show.html.twig', [
            'category' => $category,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="categories_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Categories $category): Response
    {
        $form = $this->createForm(CategoriesType::class, $category);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('categories_index');
        }

        return $this->render('categories/edit.html.twig', [
            'category' => $category,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="categories_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Categories $category): Response
    {
        if ($this->isCsrfTokenValid('delete'.$category->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($category);
            $entityManager->flush();
        }

        return $this->redirectToRoute('categories_index');
    }
}

src/Controller/Annonce/ProprietaireController.php
<?php

namespace App\Controller\Annonce;

use App\Entity\Notification;
use App\Entity\User;
use App\Repository\AnnoncesRepository;
use App\Repository\UserRepository;
use App\Service\NotificationService;
use App\Service\PaginationService;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/annonces-proprietaire/")
 */
class ProprietaireController extends AbstractController
{
    private $repAnnonce;
    private $repUser;

    public function __construct(AnnoncesRepository $repAnnonce, UserRepository $repUser)
    {
        $this->repAnnonce = $repAnnonce;
        $this->repUser    = $repUser;
	}


    /**
     * @Route("{proprietaire}/{pseudo}", name="proprietaire_annonce", methods={"GET"})
     */
	public function index(Request $request, User $proprietaire, string $pseudo, PaginationService $paginator) : Response
	{
        if ($proprietaire == null)
        {
            return $this->redirectToRoute('accueil');
		}

        $isFollower = false;
        if( $this->getUser() )
        {
            $isFollower = $this->repUser->isFollowedBy( $proprietaire, $this->getUser() );
        }

        $query         = $this->repAnnonce->findMesAnnonces($proprietaire->getId());
        $annonces      = $paginator->paginate($query, $request->query->getInt('page', 1), 40);
        $annonce_titre = $proprietaire->getPseudo() . ' annonces';
        $discr         = strpos(get_class($proprietaire), 'Professionnel');

        return $this->render('annonces/proprietaire.html.twig', [
            'annonces' => $annonces,
            'discr'    => $discr,
            'proprietaire'  => $proprietaire,
            'kilouwersCount'=> $this->repUser->countKilouwers( $proprietaire ),
            'annoncesCount' => $this->repUser->countAnnonces( $proprietaire ),
            'followed'      => $isFollower,
            'annonce_titre' => $annonce_titre
        ]);
    }


    /**
     * @Route("{proprietaire}", name="proprietaire_follow", methods={"GET"})
     */
	public function follow(User $proprietaire, NotificationService $notificationService) : Response
	{
        $user = $this->getUser();
        if( $user && $user->getId() !== $proprietaire->getId() )
        {
            $isFollower = $this->repUser->isFollowedBy( $proprietaire, $user );

            if( $isFollower > 0 )
            {
                $proprietaire->removeKilouwer( $user );
            }
            else
            {
                $proprietaire->addKilouwer( $user );

                $notification = new Notification();
                $destinataire = $proprietaire;
                $photo        = '/uploads/avatar/'. $user->getAvatar();

                $notification->setDeclencheur( $user );
                $notification->setDestinataire( $destinataire );
                $notification->setMessage('<strong>'. $destinataire->getNomComplet() .'</strong> vous suit sur kiloukoi!');
                $notification->setRoute( $this->generateUrl('location_en_cours') );
                $notification->setPhoto( $photo );

                $notificationService->send($notification, $destinataire);
            }

            $em = $this->getDoctrine()->getManager();
            $em->persist($proprietaire);
            $em->flush();

            $response = [
                'status'    => ($isFollower > 0) ? 0 : 1,
                'kilouwers' => $this->repUser->countKilouwers( $proprietaire )
            ];

            return new Response( json_encode($response) );
        }
    }
}

templates/annonces/_delete_form.html.twig
<form method="post" style="display: inline;" action="{{ path('annonces_delete', {'id': annonce.id}) }}" onsubmit="return confirm('Voulez vous vraiment supprimer ?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ annonce.id) }}">
    {% if style is defined and style == "show" %}
        <button class="btn btn-danger">Supprimer</button>
    {% else %}
        <button class="p-0 btn btn-link text-danger"  style="font-size: .8rem;">Supprimer</button>
    {% endif %}
</form>

templates/annonces/list-base.html.twig
{% extends 'base.html.twig' %}

{% set annonce_titre = annonce_titre is defined ? annonce_titre : "Mes annonces" %}
{% block title %}
	{{ annonce_titre }}
{% endblock %}

{% block stylesheets %}
	<link rel="stylesheet" href="{{ asset('css/ad-list.css') }}">
	<link rel="stylesheet" href="{{ asset('../css/ad-style.css') }}">
	<style>
		.card-body-ad-list {
			padding-top: 0;
			padding-left: 0;
			padding-right: 0;
		}

		.row_ad {
			margin-left: 0 !important;
			margin-right: 0 !important;
		}
	</style>

{% endblock %}

{% block body %}
	<div class="mt-5"></div>
	{% include "annonces/list.html.twig" %}

{% endblock %}

templates/annonces/list.html.twig
	<div class="container mt-2 mb-3">
		<div class="row mb-3">
			<div class="col-lg-10 offset-lg-1">
				<div class="row">
					<div class="offset-1 col-10 offset-sm-0 col-sm-12 offset-md-0 offset-lg-0 col-lg-12">
						<div class="card shadow-kiloukoi">
							
							<h1 class="h3 text-center text-muted pt-2">{{ annonce_titre }}</h1>
							{% if annonces|length == 0 %}
								<div class="card-body">
									<div class="alert alert-warning text-center">
										Aucune annonce !
									</div>
								</div>
							{% endif %}
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>

	<div class="container">
		<div class="row">
			<div class="col-lg-10 offset-lg-1">
				<div class="row card-deck">
					<!-- mostViewedAds defined -->
					{% if mostViewedAds is defined %}
						<div class="col-lg-12 col-md-12">
							<div class="row">
								{% for annonce in annonces %}
									{% set slug = annonce.slug == '' ? 'annonces_' : annonce.slug %}
									<div class="col-10 offset-1 offset-sm-0 col-sm-12 offset-md-0 offset-lg-0 col-md-12 col-lg-12 mb-3">
										<div class="card m-auto shadow-kiloukoi" style="">
										<!-- div class="row px-0" -->
											<div class="card-body card-body-ad-list">
												<div class="row row_ad">
													{% if annonce.photo|length > 0 %}
														<div class="col-lg-3 col-md-4 col-sm-5 col-12 text-center px-0 py-0 ad-img-container fill bg-light" style="position:relative">
															<a href="{{ path('annonces_show', {id: annonce.id, slug: slug }) }}" style="" class="overflow-hidden text-center">
																<img src="{{ asset("uploads/" ~ annonce.photo[0].url)| imagine_filter('thumb') }}" class="m-auto kiloukoisAdImage" alt="...">
															</a>
														</div>
													{% else %}
														<div class="col-lg-3 col-md-4 col-sm-5 col-12 text-center bg-light px-2 py-2 ad-img-container" style="position:relative;">
															<a href="{{ path('annonces_show', {id: annonce.id, slug: slug }) }}" style="line-height:" class="overflow-hidden text-center">
																<img src="{{ asset('image/logo-fond-blanc.png') }}" class="card-img-top m-auto p-3 img-logo-kilouks" style="" alt="...">
															</a>
														</div>
													{% endif %}
													

													<div class="col-lg-9 col-md-8 col-sm-7 col-12 pl-4"> 
														<!-- div class="card-body py-2 px-3 text-left" -->
														<div class="row">
															<div class="col-sm-10 {% if app.user and app.user.id != annonce.user.id %}  col-9 {% else %} col-12 {% endif %}" >
																<h3 class="card-title text-primary mb-2 padding-col-lg-nine" style="font-size: 1.35rem;">
																	<strong><a href="{{ path('annonces_show', {id: annonce.id, slug: slug }) }}" >{{ annonce.titre |capitalize }}</a></strong>
																</h3>
															</div>
															{% if app.user and app.user.id != annonce.user.id %}
																<div class="col-sm-2 col-3 text-right" title="Favoris">
																	{% if annonce.userFavoris|length == 0 %}
																		<span class="px-2 mr-2" data="{{ annonce.id }}">
																			<i class="far fa-heart padding-col-lg-nine"></i>
																		</span>
																	{% else %}
																		<span class="px-2 mr-2" data="{{ annonce.id }}">
																			<i class="fa fa-heart text-danger pt-2"></i>
																		</span>
																	{% endif %}
																</div>
															{% endif %}
														</div>

														<div class="details pt-2" style="font-size: 1rem;position:relative;">
															<p class="card-text mb-0"><strong>Prix : </strong>{{ annonce.prix }}€ /{{ annonce.type ? annonce.type.libelle : "mois" }}</p>
															<p class="card-text mb-0"><strong>Caution : </strong>{{ annonce.caution }} €</p>
															<p class="card-text mb-0"> {{ annonce.categorie.libelle }} {% if annonce.sousCategorie is not null %}/ {{ annonce.sousCategorie.libelle }}{% endif %}</p>
															<!-- p class="card-text text-justify text-description-henintsoa mb-0 "><strong class="text-success">Description : </strong>  {#{ annonce.description | slice(0, 46) }#} {#% if annonce.description|length > 46 %} ... {% endif %#} </p -->
															<!-- p class="card-text mb-0"><strong class="text-success">Propriétaire : </strong><a href="{#{ path('proprietaire_annonce', {proprietaire: annonce.user.id, pseudo: annonce.user.pseudo}) }#}">{#{ annonce.user.pseudo }#}</a></p -->
														</div>

														<div class="row row_ad row_ad_bottom pt-2 mb-0">
															{% if app.user and app.user.id == annonce.user.id %}
																<div class="col text-left mt-2 pl-0 pb-2 ad-form-modifs">
																	<a href="{{ path('annonces_edit', {'id': annonce.id}) }}" class="p-0 btn btn-link text-info" style="font-size: .8rem;">Modifier</a>
																	{{ include('annonces/_delete_form.html.twig') }}
																</div>
															{% else %}
																<div class="col text-left mt-2 pl-0">
																	<span style="font-size:0.95rem;"><i class="fa fa-eye"></i> {{ annonce.visite | number_format }}</span>
																</div>
															{% endif %}
															<div class="col-lg-4 col-md-4 col-sm-4 col-6 mt-2 proprietary-name">
																<a class="" href="{{ path('proprietaire_annonce', {proprietaire: annonce.user.id, pseudo: annonce.user.pseudo}) }}"><small>{{ annonce.user.pseudo }} </small></a> <span class="badge badge-pill badge-light ml-2 border">{{ annonce.user.className == "Professionnel" ? "PRO" : ""}}</span>
															</div>
															<div class="col-lg-2 col-md-3 col-sm-4 col-4 px-2 py-2 date-ad text-right">
																<small class="text-muted">{{ annonce.dateModification | date("d/m/Y") }}</small>
															</div>
														</div>
														<!-- /div -->

														<!-- /div -->
													</div>
												</div>
												<!-- div class="card-footer text-right p-0 bg-white" style="font-size: .8rem;">
													
												</div -->
											</div>
										<!--/div-->
										</div>
									</div>
								{% endfor %}
							</div>
						</div>
					{% else %}
						<div class="col-lg-12 col-md-12">
							<div class="row">
								{% for annonce in annonces %}
									{% set slug = annonce.slug == '' ? 'annonces_' : annonce.slug %}
									<div class="col-10 offset-1 offset-sm-0 col-sm-12 offset-md-0 offset-lg-0 col-md-12 col-lg-12 mb-3">
										<div class="card m-auto shadow-kiloukoi" style="">
										<!-- div class="row px-0" -->
											<div class="card-body card-body-ad-list">
												<div class="row row_ad">
													{% if annonce.photo|length > 0 %}
														<div class="col-lg-3 col-md-4 col-sm-5 col-12 text-center px-0 py-0 ad-img-container fill bg-light" style="position:relative">
															<a href="{{ path('annonces_show', {id: annonce.id, slug: slug }) }}" style="" class="overflow-hidden text-center">
																<img src="{{ asset("uploads/" ~ annonce.photo[0].url)| imagine_filter('thumb') }}" class="m-auto kiloukoisAdImage" alt="...">
															</a>
														</div>
													{% else %}
														<div class="col-lg-3 col-md-4 col-sm-5 col-12 text-center bg-light px-2 py-2 ad-img-container" style="position:relative;">
															<a href="{{ path('annonces_show', {id: annonce.id, slug: slug }) }}" style="line-height:" class="overflow-hidden text-center">
																<img src="{{ asset('image/logo-fond-blanc.png') }}" class="card-img-top m-auto p-3 img-logo-kilouks" style="" alt="...">
															</a>
														</div>
													{% endif %}
													

													<div class="col-lg-9 col-md-8 col-sm-7 col-12 pl-4"> 
														<!-- div class="card-body py-2 px-3 text-left" -->
														<div class="row">
															<div class="col-sm-10 {% if app.user and app.user.id != annonce.user.id %}  col-9 {% else %} col-12 {% endif %}" >
																<h3 class="card-title text-primary mb-2 padding-col-lg-nine" style="font-size: 1.35rem;">
																	<strong><a href="{{ path('annonces_show', {id: annonce.id, slug: slug }) }}" >{{ annonce.titre |capitalize }}</a></strong>
																</h3>
															</div>
															{% if app.user and app.user.id != annonce.user.id %}
																<div class="col-sm-2 col-3 text-right" title="Favoris">
																	{% if annonce.userFavoris|length == 0 %}
																		<span class="px-2 mr-2" data="{{ annonce.id }}">
																			<i class="far fa-heart padding-col-lg-nine"></i>
																		</span>
																	{% else %}
																		<span class="px-2 mr-2" data="{{ annonce.id }}">
																			<i class="fa fa-heart text-danger pt-2"></i>
																		</span>
																	{% endif %}
																</div>
															{% endif %}
														</div>

														<div class="details pt-2" style="font-size: 1rem;position:relative;">
															<p class="card-text mb-0"><strong>Prix : </strong>{{ annonce.prix }}€ /{{ annonce.type ? annonce.type.libelle : "mois" }}</p>
															<p class="card-text mb-0"><strong>Caution : </strong>{{ annonce.caution }} €</p>
															<p class="card-text mb-0"> {{ annonce.categorie.libelle }} {% if annonce.sousCategorie is not null %}/ {{ annonce.sousCategorie.libelle }}{% endif %}</p>
															<!-- p class="card-text text-justify text-description-henintsoa mb-0 "><strong class="text-success">Description : </strong>  {#{ annonce.description | slice(0, 46) }#} {#% if annonce.description|length > 46 %} ... {% endif %#} </p -->
															<!-- p class="card-text mb-0"><strong class="text-success">Propriétaire : </strong><a href="{#{ path('proprietaire_annonce', {proprietaire: annonce.user.id, pseudo: annonce.user.pseudo}) }#}">{#{ annonce.user.pseudo }#}</a></p -->
														</div>

														<div class="row row_ad row_ad_bottom pt-2 mb-0">
															{% if app.user and app.user.id == annonce.user.id %}
																<div class="col text-left mt-2 pl-0 pb-2 ad-form-modifs">
																	<a href="{{ path('annonces_edit', {'id': annonce.id}) }}" class="p-0 btn btn-link text-info" style="font-size: .8rem;">Modifier</a>
																	{{ include('annonces/_delete_form.html.twig') }}
																</div>
															{% else %}
																<div class="col text-left mt-2 pl-0">
																	<span style="font-size:0.95rem;"><i class="fa fa-eye"></i> {{ annonce.visite | number_format }}</span>
																</div>
															{% endif %}
															<div class="col-lg-4 col-md-4 col-sm-4 col-6 mt-2 proprietary-name">
																<a class="" href="{{ path('proprietaire_annonce', {proprietaire: annonce.user.id, pseudo: annonce.user.pseudo}) }}"><small>{{ annonce.user.pseudo }}</small></a> <span class="badge badge-pill badge-light ml-2 border">{{ annonce.user.className == "Professionnel" ? "PRO" : ""}}</span>
															</div>
															<div class="col-lg-2 col-md-3 col-sm-4 col-4 px-2 py-2 date-ad text-right">
																<small class="text-muted">{{ annonce.dateModification | date("d/m/Y") }}</small>
															</div>
														</div>
														<!-- /div -->

														<!-- /div -->
													</div>
												</div>
												<!-- div class="card-footer text-right p-0 bg-white" style="font-size: .8rem;">
													
												</div -->
											</div>
										<!--/div-->
										</div>
									</div>
								{% endfor %}
							</div>
						</div>
					{% endif %}	
				</div>

				{% include "pagination.html.twig"  with { count: annonces.count, max: annonces.query.maxResults } %}
			</div>
		</div>
	</div>