src/Entity/Conversation.php
<?php

namespace App\Entity;

use App\Repository\ConversationRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ConversationRepository::class)
 */
class Conversation
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="datetime")
     */
    private $derniere_lecture;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="conversations")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user_1;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="conversations")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user_2;

    /**
     * @ORM\OneToMany(targetEntity=Message::class, mappedBy="conversation", orphanRemoval=true)
     */
    private $messages;
    
    /**
     * @ORM\Column(type="boolean", options={"default" : false})
     */
    private $lu_1;

    /**
     * @ORM\Column(type="boolean", options={"default" : false})
     */
    private $lu_2;

    /**
     * @ORM\ManyToMany(targetEntity=Location::class, inversedBy="conversations")
     */
    private $locations;

    public function __construct()
    {
        $this->messages = new ArrayCollection();
        $this->derniere_lecture = new \DateTime();
        $this->annonces = new ArrayCollection();
        $this->locations = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDerniereLecture(): ?\DateTimeInterface
    {
        return $this->derniere_lecture;
    }

    public function setDerniereLecture(\DateTimeInterface $derniere_lecture): self
    {
        $this->derniere_lecture = $derniere_lecture;

        return $this;
    }

    /**
     * @return Collection|Message[]
     */
    public function getMessages(): Collection
    {
        return $this->messages;
    }

    public function addMessage(Message $message): self
    {
        if (!$this->messages->contains($message)) {
            $this->messages[] = $message;
            $message->setConversation($this);
        }

        return $this;
    }

    public function removeMessage(Message $message): self
    {
        if ($this->messages->contains($message)) {
            $this->messages->removeElement($message);
            // set the owning side to null (unless already changed)
            if ($message->getConversation() === $this) {
                $message->setConversation(null);
            }
        }

        return $this;
    }

    public function getUser1(): ?User
    {
        return $this->user_1;
    }

    public function setUser1(?User $user_1): self
    {
        $this->user_1 = $user_1;

        return $this;
    }


    public function getUser2(): ?User
    {
        return $this->user_2;
    }

    public function setUser2(?User $user_2): self
    {
        $this->user_2 = $user_2;

        return $this;
    }

    public function getLu1(): ?bool
    {
        return $this->lu_1;
    }

    public function setLu1(bool $lu_1): self
    {
        $this->lu_1 = $lu_1;

        return $this;
    }

    public function getLu2(): ?bool
    {
        return $this->lu_2;
    }

    public function setLu2(bool $lu_2): self
    {
        $this->lu_2 = $lu_2;

        return $this;
    }

    public function removeAnnonce(Annonces $annonce): self
    {
        $this->annonces->removeElement($annonce);

        return $this;
    }

    /**
     * @return Collection|Location[]
     */
    public function getLocations(): Collection
    {
        return $this->locations;
    }

    public function addLocation(Location $location): self
    {
        if (!$this->locations->contains($location)) {
            $this->locations[] = $location;
        }

        return $this;
    }

    public function removeLocation(Location $location): self
    {
        $this->locations->removeElement($location);

        return $this;
    }
}

src/Entity/Particulier.php
<?php

namespace App\Entity;

use App\Repository\ParticulierRepository;
use Doctrine\ORM\Mapping as ORM;

use MangoPay\MangoPayApi;
use MangoPay\UserNatural;
use MangoPay\Wallet;

/**
 * @ORM\Entity(repositoryClass=ParticulierRepository::class)
 */
class Particulier extends User
{
    /**
     * @ORM\Column(type="string", length=50)
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $prenom;

    public function getNomComplet(): string
    {
        return $this->nom . ' ' . $this->prenom;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

}

src/Form/ConversationType.php
<?php

namespace App\Form;

use App\Entity\Conversation;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ConversationType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('derniere_lecture')
            ->add('user')
            ->add('user_destination')
            ->add('annonce')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Conversation::class,
        ]);
    }
}

src/Controller/Conversation/ConversationController.php
<?php

namespace App\Controller\Conversation;

use App\Entity\Location;
use App\Entity\Conversation;
use App\Entity\Message;
use App\Entity\User;
use App\Repository\ConversationRepository;
use App\Repository\LocationRepository;
use App\Repository\MessageRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Mercure\Publisher;
use Symfony\Component\Mercure\PublisherInterface;
use Symfony\Component\Mercure\Update;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Serializer\SerializerInterface;

/**
 * @Route("/conversation")
 */
class ConversationController extends AbstractController
{
    private $conversationRepo;
    private $messageRepo;
    private $locationsRepository;

    public function __construct(ConversationRepository $conversationRepository, MessageRepository $messageRepository, LocationRepository $locationsRepository)
    {
        $this->conversationRepo = $conversationRepository;
        $this->messageRepo      = $messageRepository;
        $this->locationsRepository = $locationsRepository;
    }

    /**
     * @Route("/", name="conversation_index", methods={"get"})
     */
    public function index()
    {
        $user          = $this->getUser();
        $conversations = $this->conversationRepo->findByUserQuery($user->getId())->getResult();

        if (count($conversations) > 0) {
            /**
             * @var(Conversation $conversationEncours)
             */
            $conversationEncours = $conversations[0];
            return $this->showConversation($conversationEncours, $conversations);
        } else {
            return $this->render('conversation/erreur.html.twig', [
                'error' => "Vous n'avez aucune conversation!"
            ]);
        }
    }

    /**
     * @Route("/messages/{location}/{destinataire}", name="conversation_messages_new", methods={"post"})
     */
    public function nouveauMessage(Location $location, User $destinataire, Request $request, PublisherInterface $publisher, SerializerInterface $serializer)
    {
        $expediteur = $this->getUser();
        if ($destinataire->getId() == $expediteur->getId()) {
            return $this->render('conversation/erreur.html.twig', [
                'error' => "Vous ne pouvez pas envoyer un message à vous même!"
            ]);
        }

        $message      = new Message();
        $conversation = $this->conversationRepo->findOneWith($destinataire->getId(), $expediteur->getId());
        if ($conversation == null) {
            $conversation = new Conversation();

            $conversation->setUser1($expediteur);
            $conversation->setUser2($destinataire);
            $conversation->addLocation($location);
        } else {
            if (!$conversation->getLocations()->contains($location)) {
                $conversation->addLocation($location);
            }
        }

        // mark conversation as read by the sender and unread by the receiver
        if ($conversation->getUser1()->getId() == $expediteur->getId()) {
            $conversation->setLu1(true);
            $conversation->setLu2(false);
        } else {
            $conversation->setLu1(false);
            $conversation->setLu2(true);
        }

        $message->setConversation($conversation);
        $message->setUser($expediteur);
        $message->setContenue($request->get("contenue"));

        $entityManager = $this->getDoctrine()->getManager();
        $entityManager->persist($conversation);
        $entityManager->persist($message);
        $entityManager->flush();

        $conversation->getMessages()->add($message);
        $serialized = $serializer->serialize([
            'user' => [
                'id'       => $expediteur->getId(),
                'avatar'   =>  '/uploads/avatar/' . $expediteur->getAvatar(),
                'fullName' => $expediteur->getNomComplet()
            ],
            'content' => $message->getContenue(),
            'date'    => $message->getDate()->format('d/m/Y | H:m'),
            'conversation' => $conversation->getId(),
            'path'    => $this->generateUrl('conversation_show', ['id' => $conversation->getId()]),
            'unread'  => $this->conversationRepo->countUnreadBy($destinataire),
            'type'    => 'message',
        ], 'json');

        $publisher(new Update(
            [$_ENV['KILOUKOI_S_MERCURE_SUBSCRIBER_URL'] . $destinataire->getId()],
            $serialized,
            true,
        ));

        if ($request->isXmlHttpRequest()) {
            return new Response($serialized);
        } else {
            return $this->redirectToRoute('conversation_show', ['id' => $conversation->getId()]);
        }
    }

    /**
     * @Route("/get-unread", name="conversation_unread", methods={"get"})
     */
    public function getUnreadMessages(Request $request): Response
    {
        if ($request->isXmlHttpRequest()) {
            $unread = $this->conversationRepo->countUnreadBy($this->getUser());
            return new Response(json_encode(['unread' => $unread]));
        } else {
            return new Response(null);
        }
    }

    /**
     * @Route("/{id}", name="conversation_show", methods={"get"})
     */
    public function show(Conversation $conversation): Response
    {
        return $this->showConversation($conversation);
    }

    /**
     * @Route("/{id}", name="conversation_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Conversation $conversation): Response
    {
        if ($this->isCsrfTokenValid('delete' . $conversation->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($conversation);
            $entityManager->flush();
        }

        return $this->redirectToRoute('conversation_index');
    }

    private function showConversation(Conversation $conversationEncours, array $conversations = []): Response
    {
        $user         = $this->getUser();
        $messages     = $this->messageRepo->findByConversation($conversationEncours->getId())->getResult();
        $destinataire = ($user->getId() == $conversationEncours->getUser1()->getId()) ? $conversationEncours->getUser2() : $conversationEncours->getUser1();
        $mercureHubUrlDeux = $_ENV['KILOUKOI_MERCURE_HUB_URL_TWO'];
        $mercureGeneralSubscriberUrl = $_ENV['MERCURE_GENERAL_PUBLISH_URL'];

        if (empty($conversations)) {
            $conversations = $this->conversationRepo->findByUserQuery($user->getId())->getResult();
        }

        // mark conversation as read if it is not
        if ($conversationEncours->getUser1()->getId() == $user->getId() && !$conversationEncours->getLu1()) {
            $conversationEncours->setLu1(true);
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($conversationEncours);
            $entityManager->flush();
        } else if ($conversationEncours->getUser2()->getId() == $user->getId() && !$conversationEncours->getLu2()) {
            $conversationEncours->setLu2(true);
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($conversationEncours);
            $entityManager->flush();
        }

        return $this->render('conversation/index.html.twig', [
            'conversations'       => $conversations,
            'conversationEncours' => $conversationEncours,
            'messages'            => $messages,                               // Messages de la conversation en cours
            'location'            => $conversationEncours->getLocations()[0], // Location raccorder à la conversation en cours
            'locations'            => $conversationEncours->getLocations(), // Location raccorder à la conversation en cours
            'destinataire'        => $destinataire,                            // Déstinataire des messages de la conversation en cours
            'mercureHubUrlDeux' => $mercureHubUrlDeux,
            'mercureGeneralSubscriberUrl' => $mercureGeneralSubscriberUrl
        ]);
    }
}

templates/conversation/_delete_form.html.twig
<form method="post" action="{{ path('conversation_delete', {'id': conversation.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ conversation.id) }}">
    <button class="btn">Delete</button>
</form>

templates/conversation/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Conversation{% endblock %}

{% block body %}
    <h1>Edit Conversation</h1>

    {{ include('conversation/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('conversation_index') }}">back to list</a>

    {{ include('conversation/_delete_form.html.twig') }}
{% endblock %}

templates/conversation/erreur.html.twig
{% extends 'base.html.twig' %}

{% block title %}Messages{% endblock %}

{% block body %}

<!-- Begin Page Content -->
<div class="container">

	<div class="card">
		<div class="card-body text-danger d-flex align-items-center" style="height: 205px;">
			<div class="m-auto" style="font-size: 1.5rem;">
				{% if error is defined %}
					{{ error | capitalize}}
				{% else %}
					Vous n'avez aucune conversation!
				{% endif %}
			</div>
		</div>
	</div>
</div>

{% endblock %}

{% block javascripts %}
	 {{ parent() }}
	 <script src="{{ asset('/js/message.js') }}"></script>
{% endblock %}

templates/conversation/index-old.html.twig
{% extends 'base.html.twig' %}

{% block title %}Messages{% endblock %}

{% block body %}

<!-- Begin Page Content -->
<div class="container-fluid">

	<div class="row rounded-lg overflow-hidden shadow pt-3 mx-2">
		<!-- Users box-->
		<div class="col-12 col-md-5 col-lg-4 px-0">
			<div class="bg-white">
				<div class="p-4 bg-primary text-white">
					<h2 class="h5 mb-0 py-1">Messages</2>
				</div>

				<div class="messages-box border-right border-primary" style="height: calc(100vh - 200px);overflow-y:auto;">
					<div id="conversations" class="list-group rounded-0">

						{% for conversation in conversations %}
							{% set active = (conversationEncours.id == conversation.id) %}
							{% set read   = (app.user.id == conversation.user1.id and conversation.lu1) or (app.user.id == conversation.user2.id and conversation.lu2) %}

							<a id="conversation-{{ conversation.id }}" href="{{ path('conversation_show', {'id': conversation.id}) }}" class="list-group-item list-group-item-action rounded-0 {{ active ? 'list-group-item-primary' : (read ? 'list-group-item-light text-muted ' : 'list-group-item-info text-muted ') }}">
								<div class="media">
									{% if conversation.user1.id == app.user.id %}
										<img src="{{ asset('uploads/avatar/') ~ conversation.user2.avatar }}" alt="user" width="50" height="50" class="rounded-circle">
									{% else %}
										<img src="{{ asset('uploads/avatar/') ~ conversation.user1.avatar }}" alt="user" width="50" height="50" class="rounded-circle">
									{% endif %}
									
									<div class="media-body ml-3">
										<div class="d-flex align-items-center justify-content-between mb-0">
											{% if conversation.user1.id == app.user.id %}
												<h6 class="mb-0" style="font-weight: bold;">{{ conversation.user2.nomComplet }}</h6>
											{% else %}
												<h6 class="mb-0" style="font-weight: bold;">{{ conversation.user1.nomComplet }}</h6>
											{% endif %}
											<small style="font-size: 60%;" class="conversation-date">{{ conversation.messages[0].date | date("d/m/Y | H:m") }}</small>
										</div>
										<p class="font-italic mb-0 text-small conversation-content">
											{% if conversation.messages[0].user.id == app.user.id %}
												<small style="font-weight: bold;">Moi: </small>
											{% endif %}
											<small>{{ conversation.messages[0].contenue }}</small>
										</p>
									</div>
								</div>
							</a>
							
							{% set i = 1 %}
						{% endfor %}
						
					</div>
				</div>
			</div>
		</div>

		<!-- Chat Box-->
		<div class="col-12 col-md-7 col-lg-8 px-0 bg-white">
			{# Reciever name #}
			<div class="p-4 bg-primary text-white border-left border-white">
				<h2 class="h5 mb-0 py-1">{{ destinataire.nomComplet }}</h2>
			</div>

			<div class="chat-box w-100" >
				<div id="messageBody" data="chat-{{ conversationEncours.id }}" class="px-4 py-2" style="height: calc(100vh - 300px);overflow-y:auto;">
					{% for message in messages %}
						{% if message.user.id == app.user.id %}
							<!-- Reciever Message-->
							<div class="media w-50 ml-auto">
								<div class="media-body mb-2">
									<div class="bg-primary rounded py-2 px-3">
										<p class="text-small mb-0 text-white">{{ message.contenue }}</p>
									</div>
									<small class="small text-muted">{{ message.date | date("d/m/Y | H:m") }}</small>
								</div>
							</div>
						{% else %}
							<!-- Sender Message-->
							<div class="media w-50">
								<img src="{{ asset('uploads/avatar/') ~ message.user.avatar }}" alt="user" width="50" height="50" class="rounded-circle">
								<div class="media-body mb-2 ml-3">
									<div class="bg-light rounded py-2 px-3">
										<p class="text-small mb-0 text-muted">{{ message.contenue }}</p>
									</div>
									<small class="small text-muted">{{ message.date | date("d/m/Y | H:m") }}</small>
								</div>
							</div>
						{% endif %}
					{% endfor %}
				</div>

				<!-- Typing area -->
				<form id="message-form" method="POST" action="{{ path('conversation_messages_new', { location: location.id, destinataire: destinataire.id }) }}" class="bg-light border border-primary rounded-right w-100">
					<div class="input-group" >
						<textarea type="text" placeholder="Type a message" name="contenue" aria-describedby="message-submit" class="message-content form-control rounded-0 border-0 py-2 bg-light"  style="height: 100px;"></textarea>
						<div class="input-group-append">
							<button id="message-submit" type="submit" class="btn btn-primary">
								<i class="fa fa-paper-plane"></i>
								<span class="spinner-border spinner-border-sm d-none" role="status" aria-hidden="true"></span>
							</button>
						</div>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>

{% endblock %}

{% block javascripts %}
	 {{ parent() }}
	 <script src="{{ asset('/js/message.js') }}"></script>
{% endblock %}

templates/conversation/index.html.twig
{% extends 'base.html.twig' %}

{% block stylesheets %}
	<link rel="stylesheet" href="{{ asset('/css/conversation.css') }}">
{% endblock %}

{% block title %}Messages
{% endblock %}

{% block body %}


	<div class="row mt-2">
		<div class="col-lg-10 offset-lg-1 col-md-12">
			<div
				class="row rounded-lg overflow-hidden">
				<!-- Users box-->
				<div class="col-12 col-md-5 col-lg-4">
					<div class="envParameters" data-mercure-hub-url-deux="{{ mercureHubUrlDeux }}" data-mercure-general-subscriber-url="{{ mercureGeneralSubscriberUrl }}"></div>
					<div class="conversation-conatainer">
						<div class="p-3 text-center bg-primary text-white border-bottom border-secondary">
							<h2 class="h5 mb-0 font-weight-bold">Messages</h2>
						</div>

						<div class="messages-box">
							<div id="conversations" class="list-group rounded-0">

								{% for conversation in conversations %}
									{% set active = (conversationEncours.id == conversation.id) %}
									{% set read   = (app.user.id == conversation.user1.id and conversation.lu1) or (app.user.id == conversation.user2.id and conversation.lu2) %}

									<a id="conversation-{{ conversation.id }}" href="{{ path('conversation_show', {'id': conversation.id}) }}" class="list-group-item list-group-item-action rounded-0 {{ active ? 'list-group-item-primary' : (read ? 'list-group-item-light text-muted ' : 'list-group-item-info text-muted ') }}">
										<div class="media">
											{% if conversation.user1.id == app.user.id %}
												<img src="{{ asset('uploads/avatar/') ~ conversation.user2.avatar }}" alt="user" width="40" height="40" class="rounded-circle bg-white">
											{% else %}
												<img src="{{ asset('uploads/avatar/') ~ conversation.user1.avatar }}" alt="user" width="40" height="40" class="rounded-circle bg-white">
											{% endif %}

											<div class="media-body ml-3">
												<div class="d-flex align-items-center justify-content-between mb-0">
													{% if conversation.user1.id == app.user.id %}
														<!-- h6 class="mb-0" style="font-weight: bold;">{# conversation.user2.nomComplet }#}</h6 -->
														<h6 class="mb-0" style="font-weight: bold;">{{ conversation.user2.nomComplet }}</h6>
													{% else %}
														<!-- h6 class="mb-0" style="font-weight: bold;">{#{ conversation.user1.nomComplet }#}</h6 -->
														<h6 class="mb-0" style="font-weight: bold;">{{ conversation.user1.nomComplet }}</h6>
													{% endif %}
													<small style="font-size: 60%;" class="conversation-date">{{ conversation.messages[0].date | date("d/m/Y | H:m") }}</small>
												</div>
												<p class="font-italic mb-0 text-small conversation-content">
													{% if conversation.messages[0].user.id == app.user.id %}
														<small style="font-weight: bold;">Moi:
														</small>
													{% endif %}
													<small>{{ conversation.messages[0].contenue | slice(0, 40) }}
														{% if conversation.messages[0].contenue|length > 40 %}...
														{% endif %}
													</small>
												</p>
											</div>
										</div>
									</a>

									{% set i = 1 %}
								{% endfor %}

							</div>
						</div>
					</div>
				</div>

				<!-- Chat Box-->
				<div
					class="col-12 col-md-7 col-lg-8">
					{# Reciever name #}
					<div class="conversation-conatainer">
						<div class="{#row#} border-bottom border-secondary bg-primary" id="messages-header">
							<div class="media py-2 col-6">
								<img src="{{ asset('uploads/avatar/') ~ destinataire.avatar }}" alt="user" width="40" height="40" class="rounded-circle bg-white ml-3">

								<div class="media-body ml-3">
									<div class="d-flex align-items-center justify-content-between mb-0">
										<h6 class="mb-0 text-white font-weight-bold">{{ destinataire.nomComplet }}</h6>
									</div>
									<p class="text-white small mt-1 m-0">En ligne</p>
								</div>
							</div>

							<div class="col-6"></div>
						</div>

						<div class="chat-box w-100">
							<div id="messageBody" data="chat-{{ conversationEncours.id }}" class="px-4 py-2">
								{% for message in messages %}
									{% if message.user.id == app.user.id %}
										<!-- Reciever Message-->
										<div class="media w-50 ml-auto">
											<div class="media-body mb-2">
												<div class="bg-primary rounded py-2 px-3">
													<p class="text-small mb-0 text-white">{{ message.contenue | nl2br }}</p>
												</div>
												<small class="small">{{ message.date | date("d/m/Y | H:m") }}</small>
											</div>
										</div>
									{% else %}
										<!-- Sender Message-->
										<div class="media w-50">
											<img src="{{ asset('uploads/avatar/') ~ message.user.avatar }}" alt="user" width="40" height="40" class="rounded-circle bg-white">
											<div class="media-body mb-2 ml-3">
												<div class="rounded py-2 px-3" style="background:#e4e6eb;">
													<p class="text-small mb-0 text-muted" style="color:#050505">{{ message.contenue | nl2br }}</p>
												</div>
												<small class="small">{{ message.date | date("d/m/Y | H:m") }}</small>
											</div>
										</div>
									{% endif %}
								{% endfor %}
							</div>

							<!-- Typing area -->
							<form id="message-form" method="POST" action="{{ path('conversation_messages_new', { location: location.id, destinataire: destinataire.id }) }}" class="bg-light border border-primary rounded-right w-100">
								<div class="input-group">
									<textarea type="text" placeholder="Type a message" name="contenue" aria-describedby="message-submit" class="message-content form-control rounded-0 border-0 py-2 bg-light"></textarea>
									<div class="input-group-append">
										<button id="message-submit" type="submit" class="btn btn-primary">
											<i class="fa fa-paper-plane"></i>
											<span class="spinner-border spinner-border-sm d-none" role="status" aria-hidden="true"></span>
										</button>
									</div>
								</div>
							</form>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>

{% endblock %}

{% block javascripts %}
	{{ parent() }}
	<script src="{{ asset('/js/message.js') }}"></script>
{% endblock %}

templates/conversation/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Conversation{% endblock %}

{% block body %}
    <h1>Create new Conversation</h1>

    {{ include('conversation/_form.html.twig') }}

    <a href="{{ path('conversation_index') }}">back to list</a>
{% endblock %}

templates/conversation/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Conversation{% endblock %}

{% block body %}
    <h1>Conversation</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ conversation.id }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('conversation_index') }}">back to list</a>

    <a href="{{ path('conversation_edit', {'id': conversation.id}) }}">edit</a>

    {{ include('conversation/_delete_form.html.twig') }}
{% endblock %}