src/Entity/Particulier.php
<?php

namespace App\Entity;

use App\Repository\ParticulierRepository;
use Doctrine\ORM\Mapping as ORM;

use MangoPay\MangoPayApi;
use MangoPay\UserNatural;
use MangoPay\Wallet;

/**
 * @ORM\Entity(repositoryClass=ParticulierRepository::class)
 */
class Particulier extends User
{
    /**
     * @ORM\Column(type="string", length=50)
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $prenom;

    public function getNomComplet(): string
    {
        return $this->nom . ' ' . $this->prenom;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\UserInterface;

use Symfony\Component\Validator\Constraints as Assert;

use Doctrine\ORM\Mapping\InheritanceType;
use Doctrine\ORM\Mapping\DiscriminatorColumn;
use Doctrine\ORM\Mapping\DiscriminatorMap;
use Symfony\Component\HttpKernel\KernelInterface;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @UniqueEntity(
 *      fields={"email"},
 *      entityClass="App\Entity\User"
 * )
 * 
 * @InheritanceType("JOINED")
 * @DiscriminatorColumn(name="discr", type="string")
 * @DiscriminatorMap({"User" = "User", "Particulier" = "Particulier", "Professionnel" = "Professionnel"})
 */
class User implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     * @Assert\Email()
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $pseudo;

    /**
     * @ORM\OneToMany(targetEntity=Location::class, mappedBy="user")
     */
    private $location;

    /**
     * @ORM\OneToMany(targetEntity=Message::class, mappedBy="user", orphanRemoval=true)
     */
    private $messages;

    /**
     * @ORM\OneToMany(targetEntity=Conversation::class, mappedBy="user", orphanRemoval=true)
     */
    private $conversations;

    /**
     * @ORM\OneToMany(targetEntity=Annonces::class, mappedBy="user", orphanRemoval=true)
     */
    private $annonces;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $avatar;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_creation;

    /**
     * @ORM\Column(type="datetime")
     */
    private $dateMiseAJour;

    /**
     * @ORM\Column(type="boolean")
     */
    private $actif;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $ville;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $adresse;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $cp;

    /**
     * @ORM\Column(type="string", length=25)
     */
    private $telephone;

    /**
     * @ORM\Column(type="smallint")
     */
    private $genre;

    /**
     * @ORM\ManyToMany(targetEntity=Annonces::class, inversedBy="user_favoris")
     */
    private $favoris;

    /**
     * @ORM\OneToMany(targetEntity=Abonnement::class, mappedBy="user")
     */
    private $abonnement;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $mangoPayId;

    /**
     * @ORM\ManyToMany(targetEntity=User::class, inversedBy="kilouwees")
     */
    private $kilouwers;

    /**
     * @ORM\ManyToMany(targetEntity="User", mappedBy="kilouwers")
     */
    private $kilouwees;

    /**
     * @ORM\OneToMany(targetEntity=Notification::class, mappedBy="destinataire")
     */
    private $notifications;

    /**
     * @ORM\OneToMany(targetEntity=Note::class, mappedBy="destinataire", orphanRemoval=true)
     */
    private $notes;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $moyenneNotes;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $activation_token;
    
    public function __construct()
    {
        $this->location = new ArrayCollection();
        $this->messages = new ArrayCollection();
        $this->conversations = new ArrayCollection();
        $this->annonces = new ArrayCollection();
        $this->favoris = new ArrayCollection();
        $this->abonnement = new ArrayCollection();
        $this->kilouwers = new ArrayCollection();
        $this->notifications = new ArrayCollection();
        $this->notes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }
    public function getPseudo(): ?string
    {
        return $this->pseudo;
    }

    public function setPseudo(string $pseudo): self
    {
        $this->pseudo = $pseudo;

        return $this;
    }

    /**
     * @return Collection|Location[]
     */
    public function getLocation(): Collection
    {
        return $this->location;
    }

    public function addLocation(Location $location): self
    {
        if (!$this->location->contains($location)) {
            $this->location[] = $location;
            $location->setUser($this);
        }

        return $this;
    }

    public function removeLocation(Location $location): self
    {
        if ($this->location->contains($location)) {
            $this->location->removeElement($location);
            // set the owning side to null (unless already changed)
            if ($location->getUser() === $this) {
                $location->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Message[]
     */
    public function getMessages(): Collection
    {
        return $this->messages;
    }

    public function addMessage(Message $message): self
    {
        if (!$this->messages->contains($message)) {
            $this->messages[] = $message;
            $message->setUser($this);
        }

        return $this;
    }

    public function removeMessage(Message $message): self
    {
        if ($this->messages->contains($message)) {
            $this->messages->removeElement($message);
            // set the owning side to null (unless already changed)
            if ($message->getUser() === $this) {
                $message->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Conversation[]
     */
    public function getConversations(): Collection
    {
        return $this->conversations;
    }

    public function addConversation(Conversation $conversation): self
    {
        if (!$this->conversations->contains($conversation)) {
            $this->conversations[] = $conversation;
            $conversation->setUser($this);
        }

        return $this;
    }

    public function removeConversation(Conversation $conversation): self
    {
        if ($this->conversations->contains($conversation)) {
            $this->conversations->removeElement($conversation);
            // set the owning side to null (unless already changed)
            if ($conversation->getUser() === $this) {
                $conversation->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Annonces[]
     */
    public function getAnnonces(): Collection
    {
        return $this->annonces;
    }

    public function addAnnonce(Annonces $annonce): self
    {
        if (!$this->annonces->contains($annonce)) {
            $this->annonces[] = $annonce;
            $annonce->setUser($this);
        }

        return $this;
    }

    public function removeAnnonce(Annonces $annonce): self
    {
        if ($this->annonces->contains($annonce)) {
            $this->annonces->removeElement($annonce);
            // set the owning side to null (unless already changed)
            if ($annonce->getUser() === $this) {
                $annonce->setUser(null);
            }
        }

        return $this;
    }

    public function getAvatar(): ?string
    {
        return $this->avatar;
    }

    public function setAvatar(string $avatar): self
    {
        $this->avatar = $avatar;

        return $this;
    }

    public function getDateCreation(): ?\DateTimeInterface
    {
        return $this->date_creation;
    }

    public function setDateCreation(): self
    {
        $this->date_creation = new \Datetime();

        return $this;
    }

    public function getDateMiseAJour(): ?\DateTimeInterface
    {
        return $this->dateMiseAJour;
    }

    public function setDateMiseAJour(): self
    {
        $this->dateMiseAJour = new \Datetime();

        return $this;
    }

    public function getActif(): ?bool
    {
        return $this->actif;
    }

    public function setActif(bool $actif): self
    {
        $this->actif = $actif;

        return $this;
    }

    public function getVille(): ?string
    {
        return $this->ville;
    }

    public function setVille(string $ville): self
    {

src/Form/UserType.php
<?php

namespace App\Form;

use App\Entity\User;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\File;

class UserType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
                ->add('email', EmailType::class)
                ->add('telephone', TextType::class, ['label' => 'Téléphone'])
                ->add('genre', ChoiceType::class, [
                    'choices'  => [
                        'Homme' => 1,
                        'Femme' => 2,
                    ],
                ])
                ->add('pseudo', TextType::class)
                ->add('ville', TextType::class)
                ->add('adresse', TextType::class)
                ->add('cp', TextType::class, ['label' => 'Code postale'])
                ->add('avatar', FileType::class, [
                    'constraints' => [
                        new File([
                            'mimeTypes' => [
                                'image/*',
                            ],
                            'mimeTypesMessage' => 'Veuillez choisir une photo!',
                        ])
                    ],
                    'data_class' => null,
                    'mapped' => false
                ])
                // ->add('password', RepeatedType::class, [
                //     'type' => PasswordType::class,
                //     'invalid_message' => 'Les deux champs doivent être identiques.',
                //     'options' => ['attr' => ['class' => 'password-field']],
                //     'required' => true,
                //     'first_options'  => ['label' => 'Mot de passe'],
                //     'second_options' => ['label' => 'Confirmer votre mot de passe'],
                //     'constraints' => [
                //         new NotBlank([
                //             'message' => 'Please enter a password',
                //         ]),
                //         new Length([
                //             'min' => 6,
                //             'minMessage' => 'Entrer au moins {{ limit }} caracteres',
                //             // max length allowed by Symfony for security reasons
                //             'max' => 4096,
                //         ]),
                //     ],
                // ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => User::class,
        ]);
    }
}

templates/user/_delete_form.html.twig
<form method="post" action="{{ path('user_delete', {'id': user.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ user.id) }}">
    <button class="btn">Delete</button>
</form>

templates/user/_form.html.twig
{{ form_start(form, {'attr': {'id': 'registration_form'}} ) }}
    {{ form_errors(form) }}

    {{ form_row(form.email) }}

    {% if form.nom is defined %}
        <div class="row">
            <div class="col-md-6">
                {{ form_row(form.nom) }}
            </div>
            <div class="col-md-6">
                {{ form_row(form.prenom) }}
            </div>
        </div>
    {% endif %}
    
    {% if form.raison_social is defined %}
        <div class="row">
            <div class="col-md-6">
                {{ form_row(form.raison_social) }}
            </div>
            <div class="col-md-6">
                {{ form_row(form.siret) }}
            </div>
        </div>
    {% endif %}

    <div class="row">
        <div class="col-md-6">
            {{ form_row(form.pseudo) }}
        </div>
        <div class="col-md-6">
            {{ form_row(form.genre) }}
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            {{ form_row(form.telephone, { 'id': 'registration_phone'} ) }}
        </div>
    </div>

    <div class="row">
        <div class="col-md-6">
            {{ form_row(form.ville, { 'id': 'city', 'attr': {'autocomplete': 'off'} }) }}
        </div>
        <div class="col-md-6">
            {{ form_row(form.cp, { 'id': 'code_postal', 'attr': {'readonly': 'on'}} ) }}
        </div>
    </div>

    {{ form_row(form.adresse, { 'id': 'registration_adresse'}) }}

    {% do form.avatar.setRendered() %}

    <div class="row m-3 text-center">
        <div class="col-md-4 offset-md-4">
            <img src="{{ asset('uploads/avatar/') ~ app.user.avatar }}" alt="" class="img-fluid rounded output-image">
            <div>
                {% do form.avatar.setRendered() %}

                <label href="#" type="button" class="btn btn-info btn-block">
                    <input type="file" name="{{ form.avatar.vars.full_name }}" class="d-none input-image"> Changer d'avatar
                </label>
            </div>
        </div>
    </div>

    <div class="row m-3 text-center">
        <div class="col-md-8 offset-md-2 col-lg-4 offset-lg-4">
            {% if form_errors(form.avatar) %}
                <div id="image-validation" class="error-image alert alert-warning">{{ form.avatar.vars.errors | replace({"ERROR: ": ""}) }}</div>
            {% else %}
                <div id="image-validation" class="error-image d-none alert alert-warning"></div>
            {% endif %}
        </div>
    </div>

    {# {{ form_row(form.agreeTerms) }} #}
    
    <button type="submit" class="btn btn-primary btn-block" id="btn-submit">
        <i class="fa fa-btn fa-user"></i> Enregistrer
    </button>
{{ form_end(form) }}

templates/user/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Profil - Modification{% endblock %}

{% block stylesheets %}
    <style>
        #city-list {
            list-style: none;
            border: solid .5px var(--primary);
            position: absolute;
            width: 100%;
            z-index: 12;
            background:white;
            padding: 0;
        }

        #city-list li:hover {
            background-color: var(--success);
            color: white;
            cursor: pointer;
        }

        .form-group {
            position: relative;
        }
    </style>
{% endblock %}

{% block body %}

    <div class="container-fluid" >
        
        <div class="row">
            <div class="col-md-10 offset-md-1 col-lg-8 offset-lg-2 col-sm-12 bg-white rounded pb-3" style="margin-top: 50px;;">
                <div class="text-center">
                    <img src="{{ asset('image/logo-fond-blanc.png') }}" class="" alt="" style="height: 150px;width:auto;margin-top:-50px">
                </div>

                <div class="card" style="min-height: calc(100vh - 310px);">
                    <div class="card-body">
                        <div class="card-title">
                            <h2 class="text-success text-center">Mes infos</h2>
                        </div>

                        <div class="row">
                            <div class="col-12">
                                {{ include('user/_form.html.twig', {'button_label': 'Modifier'}) }}                                
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    <script src="{{ asset('/js/profil.js') }}"></script>
{% endblock %}

templates/user/email.html.twig
<div style="background: linear-gradient(#004E5B, #3FB5C8 60% ); color: white; text-align: center; height:auto;padding:30px;">
	<center style="max-width: 200px;height: auto;margin:auto;">
		<img class="logo" src="{{ app.request.getSchemeAndHttpHost() ~ asset('/image/logo.png') }}">
	</center>
	<h2 style="width:100%">N'achetez que le nécessaire, pour le reste il y a Kiloukoi!</h2>

	<p style="text-align:center;font-size: 1rem; padding: 20px; background: white;color: grey;border-radius: 5px;">
		<span>
			{{messages}}
		</span>
		<br>
		<span>
			Pour vérifier votre compte, clicker sur <a style="color: #004E5B" href="{{path('')}}">ce lien</a>
		</span>
	</p>
</div>

templates/user/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}User index{% endblock %}

{% block body %}
    <h1>User index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Username</th>
                <th>Password</th>
                <th>Nom</th>
                <th>Prenom</th>
                <th>Ville</th>
                <th>Cp</th>
                <th>Rue</th>
                <th>Telephone</th>
                <th>Pseudo</th>
                <th>Fonction</th>
            </tr>
        </thead>
        <tbody>
        {% for user in users %}
            <tr>
                <td>{{ user.id }}</td>
                <td>{{ user.username }}</td>
                <td>{{ user.password }}</td>
                <td>{{ user.nom }}</td>
                <td>{{ user.prenom }}</td>
                <td>{{ user.ville }}</td>
                <td>{{ user.cp }}</td>
                <td>{{ user.rue }}</td>
                <td>{{ user.telephone }}</td>
                <td>{{ user.pseudo }}</td>
                <td>
                    <a href="{{ path('user_show', {'id': user.id}) }}">show</a>
                    <a href="{{ path('user_edit', {'id': user.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="14">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('user_new') }}">Create new</a>
{% endblock %}

templates/user/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New User{% endblock %}

{% block body %}
    <h1>Create new User</h1>

    {{ include('user/_form.html.twig') }}

    <a href="{{ path('user_index') }}">back to list</a>
{% endblock %}

templates/user/userFavoris.html.twig
{% extends 'base.html.twig' %}

{% block body %}
	<div class="container">
		<div class="row">
			<div class="col-lg-10 offset-lg-1 col-md-12">
				<h1 class="h3 text-center text-primary py-3 bg-white">{{ titre }}</h1>
				{% if favoris|length == 0 %}
					<div class="card">
						<h1 class="h3 text-center text-muted pt-2">{{ annonce_titre }}</h1>
						<div class="card-body">
							<div class="alert alert-warning text-center">
								Vous n'avez pas encore de kilouwers préférés!
							</div>
						</div>
					</div>
				{% endif %}
			
				<div class="row card-deck">
					{% for result in favoris %}
						{% set user      = result[0] %}
						{% set followers = result[1] %}
						{% set annonces  = result[2] %}
						<div class="col-12 col-md-6 col-lg-4 mb-3">
							<div class="card h-100 shadow m-auto" style="max-width: 300px;">
								<a href="{{ path('proprietaire_annonce', {proprietaire: user.id, pseudo: user.pseudo }) }}" style="height: 185px;" class="text-center overflow-hidden bg-light">
                           			<img src="{{ asset("uploads/avatar/" ~ user.avatar) }}" class="card-img-top w-100 m-auto" alt="...">
								</a>

								<div class="card-body py-2 px-3 text-center">
									<h3 class="card-title text-primary mb-2" style="font-size: 1.15rem;">
										<strong><a href="{{ path('proprietaire_annonce', {proprietaire: user.id, pseudo: user.pseudo }) }}" >{{ user.nomComplet }}</a></strong>
									</h3>
									<div class="text-center text-warning mb-1">
										<i class="fas fa-star"></i>
										<i class="fas fa-star"></i>
										<i class="fas fa-star"></i>
										<i class="far fa-star"></i>
										<i class="far fa-star"></i>
									</div>
									<div class="details" style="font-size: .8rem;position:relative;">
										<p class="card-text mb-0">
											<strong class="text-success">Kilouwers : </strong>
											<span>{{ followers }}</span>
										</p>
									</div>
									<div class="details" style="font-size: .8rem;position:relative;">
										<p class="card-text mb-0">
											<strong class="text-success">Annonces en lignes : </strong>
											<span>{{ annonces }}</span>
										</p>
									</div>
								</div>
							</div>
						</div>
					{% endfor %}
				</div>

				{% include "pagination.html.twig"  with { count: favoris.count, max: favoris.query.maxResults } %}
			</div>
		</div>
	</div>
{% endblock %}